# Project information
site_name: EWEA - ANDES 
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Sunny Bhaveen Chandra
site_description: >-
  DESCRIPTION

# Repository
repo_name: practicalactionorg/ewea-andes-bolivia
repo_url: https://github.com/practicalactionorg/ewea-andes-bolivia

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: purple 
  logo: https://raw.githubusercontent.com/practicalactionorg/logos/main/iniciales-original.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/ambarja"  target="_blank" rel="noopener">Antony Barja (ambarja)</a>